# Generated by Django 3.2.13 on 2022-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spec_data',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
